name: Angular Build and Deploy

# This workflow runs ONLY on a push to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    # These permissions are required to allow the action to push to the gh-pages branch
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      # 1. Checks out your repository's code
      - name: Checkout the source code
        uses: actions/checkout@v4

      # 2. Sets up Node.js
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # 3. Installs dependencies
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --base-href /fidzulu-ui/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/fidzulu-ui

