name: Angular Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration production --base-href /fidzulu-ui/

      - name: List build folder
        run: ls -R dist/fidzulu-ui/browser

      - name: Add SPA fallback
        run: cp dist/fidzulu-ui/browser/index.html dist/fidzulu-ui/browser/404.html

      - name: Add .nojekyll
        run: touch dist/fidzulu-ui/browser/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/fidzulu-ui/browser
          publish_branch: gh-pages
